#!/usr/bin/env bash
# Live-fire test: rebuild fsf-daemon with the new ADR-0017 code,
# birth a real agent against the running Ollama backend, and dump the
# resulting soul.md so we can see actual LLM-generated Voice content.
#
# Routes the daemon at llama3.2:1b for this run (via a written .env)
# because llama3.1:8b doesn't fit in the default Docker container
# memory. The .env is written if missing; if you already have a .env
# the script leaves it alone (you should set FSF_LOCAL_MODEL yourself).
set -uo pipefail  # no -e: we want to see all diagnostic output even if a step fails
HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"

bar() { printf '\n=== %s ===\n' "$1"; }

bar "0. pre-flight: docker stack state"
docker compose ps

bar "1. ensure .env routes the daemon at llama3.2:1b (fits in 2.8 GiB)"
if [ ! -f .env ]; then
    cat > .env <<'EOF'
# Auto-generated by live-fire-voice.command — points the daemon at
# llama3.2:1b which fits in the default Docker container memory
# (~2.8 GiB seen by ollama). Bump Docker memory in Settings → Resources
# → Memory to 8+ GiB and switch back to llama3.1:8b for production use.
FSF_LOCAL_MODEL=llama3.2:1b
FSF_NARRATIVE_MAX_TOKENS=400
FSF_NARRATIVE_TEMPERATURE=0.6
EOF
    echo "wrote .env with FSF_LOCAL_MODEL=llama3.2:1b"
else
    echo ".env already exists — leaving it alone:"
    grep -E "^(FSF_LOCAL_MODEL|FSF_NARRATIVE_)" .env || \
        echo "(no FSF_LOCAL_MODEL or narrative knobs — the daemon will use its compiled defaults)"
fi

bar "2. rebuild fsf-daemon with the new ADR-0017 source"
docker compose build daemon

bar "3. recreate stack so daemon picks up the new image + .env"
# --force-recreate ensures the daemon container is replaced even if
# image tag matched a previously-running one. profile llm keeps
# fsf-ollama in the picture.
docker compose --profile llm up -d --force-recreate daemon
docker compose --profile llm up -d ollama frontend

bar "4. wait for fsf-daemon to report healthy on /healthz"
for i in $(seq 1 60); do
    if curl -fsS http://127.0.0.1:7423/healthz >/dev/null 2>&1; then
        echo "daemon healthy after ${i}s"
        break
    fi
    printf '.'
    sleep 1
done
echo

bar "5. confirm provider chain — local must be ok with llama3.2:1b loaded"
curl -fsS http://127.0.0.1:7423/runtime/provider \
    | python3 -m json.tool

bar "5b. diagnose trait engine state inside the daemon container"
echo "--- container working dir ---"
docker exec fsf-daemon pwd
echo "--- /app/config listing ---"
docker exec fsf-daemon ls -la /app/config
echo "--- /app top level ---"
docker exec fsf-daemon ls -ld /app /app/config
echo "--- whoami inside fsf-daemon ---"
docker exec fsf-daemon whoami
docker exec fsf-daemon id
echo "--- can we cat the trait tree? ---"
docker exec fsf-daemon sh -c 'head -3 /app/config/trait_tree.yaml || echo "CAT FAILED with exit $?"'
echo "--- can we open() it from python? ---"
docker exec fsf-daemon python -c "
import os
try:
    f = open('/app/config/trait_tree.yaml', 'r')
    print('open() OK, first 60 bytes:', repr(f.read(60)))
    f.close()
except Exception as e:
    print('open() FAILED:', type(e).__name__, str(e))
    print('stat:', os.stat('/app/config/trait_tree.yaml'))
"
echo "--- attempt to load TraitEngine directly ---"
docker exec fsf-daemon python -c "
import os
print('cwd:', os.getcwd())
print('FSF_TRAIT_TREE_PATH:', os.environ.get('FSF_TRAIT_TREE_PATH', '(unset → defaults)'))
from pathlib import Path
default = Path('config/trait_tree.yaml')
print('default exists?', default.exists(), '  abs:', default.resolve())
try:
    from forest_soul_forge.core.trait_engine import TraitEngine
    eng = TraitEngine(default)
    print('TraitEngine loaded OK; roles:', list(eng.roles.keys())[:3])
except Exception as e:
    print('TraitEngine load FAILED:', type(e).__name__, str(e))
"

bar "6. POST /birth with enrich_narrative=true (LLM writes the Voice)"
# -sS prints body on non-2xx; -w echoes status code so we can diagnose.
# Don't `set -e` out on a non-201 — we want to see what the server said.
HTTP_CODE_FILE=$(mktemp)
RESP="$(curl -sS -X POST http://127.0.0.1:7423/birth \
    -H 'Content-Type: application/json' \
    -w '\nHTTP_STATUS:%{http_code}' \
    -o /tmp/birth_body \
    -d '{
        "profile": {
            "role": "network_watcher",
            "trait_values": {},
            "domain_weight_overrides": {}
        },
        "agent_name": "VoiceTest",
        "agent_version": "v1",
        "owner_id": "live-fire",
        "enrich_narrative": true
    }')"
echo "$RESP"
echo "--- response body ---"
cat /tmp/birth_body
echo
echo "--- daemon logs (last 80 lines) ---"
docker compose logs --tail=80 daemon

# Reload RESP from body for the downstream parsing steps. If body
# isn't JSON (because of an error) the python parse below will fail
# loudly and we'll skip steps 7-8.
RESP="$(cat /tmp/birth_body)"

bar "7. locate the produced soul.md"
SOUL_PATH="$(echo "$RESP" | python3 -c "import sys, json; d=json.load(sys.stdin); print(d.get('soul_path',''))")"
echo "soul_path: $SOUL_PATH"

# soul_path returned by the daemon is the IN-CONTAINER path
# (/app/data/soul_generated/...). Translate to the host bind-mount.
HOST_SOUL="${SOUL_PATH/#\/app\/data/$HERE\/data}"
echo "host_path: $HOST_SOUL"

bar "8. dump narrative_* frontmatter + Voice section"
if [ -f "$HOST_SOUL" ]; then
    echo
    echo "--- narrative_* frontmatter fields ---"
    grep -E '^narrative_' "$HOST_SOUL"
    echo
    echo "--- Voice section ---"
    awk '/^## Voice$/{flag=1; print; next} /^## /{flag=0} flag{print}' "$HOST_SOUL"
    echo
    echo "(full soul.md is at: $HOST_SOUL)"
else
    echo "could not find soul.md at $HOST_SOUL — daemon may have written it elsewhere"
    echo "checking data/soul_generated/ for VoiceTest files..."
    ls -la data/soul_generated/ 2>/dev/null | grep -i voice || echo "(none)"
fi

echo
echo "Press return to close."
read -r _
