#!/bin/bash
# Burst 126 — Housekeeping bundle.
#
# Opportunistic cleanup before Burst 127 (ADR-0044 P2 kernel API
# spec). Per the Burst 125 audit, the kernel API spec needed a few
# small tidies that don't justify their own commit but together
# clean up loose ends the audit surfaced.
#
# What ships:
#
#   config/tool_catalog.yaml — two changes:
#
#     1. verifier_loop archetype backfill. ADR-0036 added the
#        verifier_loop role at v0.3 (trait_tree.yaml + genres.yaml +
#        constitution_templates.yaml all populated) but the archetype
#        kit in tool_catalog.yaml was never added — verifier_loop
#        was falling through to the verification genre's
#        genre_default_tools. Functional, but the operator surface
#        (character sheet "kit" view) showed an empty
#        standard_tools list. Backfilled to match the established
#        pattern for every other named role. Tools: memory_recall +
#        memory_verify (ADR-0036 T1) + memory_flag_contradiction
#        (ADR-0036 T2 flag-not-rewrite) + audit_chain_verify
#        (tamper-evidence) + llm_think (reasoning over verification
#        candidates) + delegate (cross-tier escalation).
#
#     2. Phase G ownership clarification. The packet_query.v1
#        deferral comment block (top of `tools:` mapping) said
#        "deferred to Phase G's planned tshark_pcap_query.v1" but
#        Burst 117 (ADR-0044) split kernel from userspace. The
#        comment now clarifies that tshark_pcap_query.v1 is a
#        USERSPACE tool — it lives in the SoulUX security distribution
#        alongside network_watcher / log_lurker / net_ninja, not in
#        the kernel ABI. Kernel ships dispatcher + governance pipeline
#        + audit chain + plugin protocol; concrete tools live in
#        userspace tool packs.
#
#   examples/audit_chain.jsonl — sync 3 live runtime entries from
#     2026-05-05 operator_companion conversation runtime testing.
#     These were generated by Alex's chat-tab smoke test against the
#     running daemon (test of llm_think.v1 dispatch through the
#     conversation runtime, which the agent's constitution didn't
#     grant — refused cleanly, audit-trail visible). Per
#     `dev-tools/check-drift.sh` discipline, the chain is the
#     canonical state on disk and should be committed when working-
#     tree drift accumulates.
#
# Verification:
#   - Full unit suite: 2,386 passing, 3 skipped (sandbox-only),
#     1 xfail (v6→v7 SQLite migration, pre-existing per Phase A
#     audit finding F-7). Zero regressions from the archetype
#     backfill.
#   - Audit chain hashes still link cleanly through entry 1121
#     (verified via `dev-tools/check-drift.sh`).
#   - Catalog integrity: 53 tools, 40 archetypes (was 39; +1 for
#     verifier_loop), 5 genre defaults.
#
# Closes the must-do precondition list for Burst 127. Untracked
# .command scripts at repo root remain for Alex's archival decision
# (commit under dev-tools/commit-bursts/, .gitignore, or delete);
# none of them are load-bearing for P2.

set -euo pipefail

cd "$(dirname "$0")"

if [ -e .git/index.lock ]; then
  echo "ERROR: .git/index.lock present. Run ./clean-git-locks.command first."
  exit 2
fi

git add config/tool_catalog.yaml examples/audit_chain.jsonl

echo "--- staged for commit ---"
git diff --cached --stat
echo "-------------------------"

git commit -m "chore: housekeeping — verifier_loop archetype + Phase G ownership + audit chain sync (B126)

Burst 126. Opportunistic cleanup before Burst 127 (ADR-0044 P2
kernel API spec). Three small tidies bundled into one commit.

config/tool_catalog.yaml — two changes:

1. verifier_loop archetype backfill. ADR-0036 added the role at
   v0.3 (trait_tree + genres + constitution_templates all
   populated) but the archetype kit was never added; verifier_loop
   was falling through to the verification genre's
   genre_default_tools. Functional, but operator surface (character
   sheet 'kit' view) showed empty standard_tools. Backfilled with
   memory_recall + memory_verify (ADR-0036 T1) +
   memory_flag_contradiction (ADR-0036 T2 flag-not-rewrite) +
   audit_chain_verify + llm_think + delegate.

2. Phase G ownership clarification. The packet_query.v1 deferral
   comment block at top of tools: mapping said 'deferred to Phase
   G's planned tshark_pcap_query.v1' but Burst 117 (ADR-0044)
   split kernel from userspace. Comment now clarifies that
   tshark_pcap_query.v1 is USERSPACE — lives in SoulUX security
   distribution alongside network_watcher / log_lurker / net_ninja,
   not in the kernel ABI. Kernel ships dispatcher + governance
   pipeline + audit chain + plugin protocol; concrete tools live in
   userspace tool packs.

examples/audit_chain.jsonl — sync 3 live runtime entries from
2026-05-05 operator_companion conversation runtime testing
(llm_think.v1 dispatch attempt that the agent's constitution
didn't grant — refused cleanly with tool_call_refused event,
audit-trail visible). Per dev-tools/check-drift.sh discipline,
the chain is canonical state on disk and should be committed when
working-tree drift accumulates.

Verification:
- Full unit suite: 2,386 passing, 3 skipped (sandbox-only),
  1 xfail (v6→v7 SQLite migration, pre-existing per Phase A
  audit finding F-7). Zero regressions from the archetype
  backfill.
- Audit chain hashes link cleanly through entry 1121 (verified
  via dev-tools/check-drift.sh).
- Catalog integrity: 53 tools, 40 archetypes (was 39; +1 for
  verifier_loop), 5 genre defaults.

Closes the must-do precondition list for Burst 127. Untracked
.command scripts at repo root remain for Alex's archival decision
(commit under dev-tools/commit-bursts/, .gitignore, or delete);
none of them are load-bearing for P2."

echo "--- commit landed ---"
git log --oneline -1

echo ""
echo "--- pushing to origin ---"
git push origin main

echo ""
echo "=== Burst 126 commit + push complete ==="
echo "Press any key to close this window."
read -n 1
